INSERT INTO STOCKS(ISSUER_NAME, SHARE_PRICE) VALUES ('AAPL', 80);
INSERT INTO STOCKS(ISSUER_NAME, SHARE_PRICE) VALUES ('NFTX', 50);
INSERT INTO STOCKS(ISSUER_NAME, SHARE_PRICE) VALUES ('GOOG', 60);
INSERT INTO ACCOUNTS(CASH) VALUES (1000);